name: Build and Release EXE

on:
  push:
    tags:
      - 'v*'    # 只有打 tag 的时候才触发，比如 v1.0 v2.1.3 这样

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'  # 你的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller addTool.py --onefile --noconsole --distpath output/dist --workpath output/build
      # 注意我这里加了 --distpath 和 --workpath，打包路径更干净，不污染源代码

    - name: Upload EXE to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: output/dist/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.TOOL_TOKEN }}
